### ISSUE TITLE
segmentation fault on branch walks

### ISSUE THREAD

**Issue by dirkjanvw** [asl/BandageNG#150] opened 2024-02-17 19:21 UTC
As mentioned in #149 I get a segmentation fault on branch `walks`, which I don't get on branch `dev` with my Macbook Pro. Example GFA file I obtained from the Minigraph-Cactus pipeline can be found here: [mc-pangenome.gfa.gz](https://github.com/asl/BandageNG/files/14320013/mc-pangenome.gfa.gz). Let me know if there is anything else I can provide to figure out why this happens.

**Comment by asl** [comment] 2024-02-18 03:58
Ok, so the problem is that `W` line appear before `L`. As we are doing stream parsing we build graph on-fly. Therefore at the time of `W` record processing there are no edges between segments / nodes. I will fix, so the proper message / exception will be thrown.

**Comment by asl** [comment] 2024-02-18 05:43
We do not segfault after https://github.com/asl/BandageNG/commit/a6adcc353e50cb16b17bae477a06582c94818672

However, the producer of this GFA should be fixed. Per GFA spec – "A valid walk must exist in the graph". We treat this quite strict as otherwise we will need essentially to save the copy of entire GFA before processing.

**Comment by dirkjanvw** [comment] 2024-02-19 17:30
Thank you for the quick fix! I now "sorted" the graph by putting all W-lines at the end of the file, I think that should solve the processing issue? However, it doesn't complete parsing. I let `BandageNG info mc-pangenome.sorted.gfa` run for an hour before I killed the process. Were you able to parse this GFA file in reasonable time?

**Comment by asl** [comment] 2024-02-19 17:31
Can you attach the new file, so I can check?

**Comment by dirkjanvw** [comment] 2024-02-19 20:36
Of course: [mc-pangenome.sorted.gfa.gz](https://github.com/asl/BandageNG/files/14336658/mc-pangenome.sorted.gfa.gz) I had to gzip the file, wheareas I ran `BandageNG info` with the uncompressed version, assuming this has no effect.

**Comment by asl** [comment] 2024-04-02 13:27
> Of course: [mc-pangenome.sorted.gfa.gz](https://github.com/asl/BandageNG/files/14336658/mc-pangenome.sorted.gfa.gz) I had to gzip the file, wheareas I ran `BandageNG info` with the uncompressed version, assuming this has no effect.

Sorry, somehow I forgot to respond. Looks like it was me reading GFA spec improperly. Need to push the fix

**Comment by asl** [comment] 2024-04-02 14:12
Should be fixed in 24907eb

**Comment by dirkjanvw** [comment] 2024-04-02 17:58
Thanks a lot, it works for me now!

**Closed as completed** 2024-07-25 22:14 UTC
