### ISSUE TITLE
Bandage-NG on Windows?

### ISSUE THREAD

**Issue by Ecoulembier** [asl/BandageNG#151] opened 2024-07-25 09:29 UTC
Would Bandage-NG be released on windows? Finding Paths specifically would be incredibly useful which I cannot do in Bandage.

**Comment by asl** [comment] 2024-07-25 15:45
Duplicate of #31 

See https://github.com/asl/BandageNG/issues/31#issuecomment-2250736527

**Closed as not planned by asl** 2024-07-25 15:45 UTC
Labels: duplicate

**Comment by asl** [comment] 2024-07-27 00:53
@Ecoulembier can you try downloading artifacts from https://github.com/asl/BandageNG/actions/runs/10119374072 and see if it works for you?

**Comment by Ecoulembier** [comment] 2024-07-27 08:29
It works for me, thanks for putting in the effort!
