### ISSUE TITLE
Crashes immediately during layout

### ISSUE THREAD

**Issue by rlorigro** [asl/BandageNG#91] opened 2022-07-15 21:18 UTC
Hi, 

I am attempting to load and draw this graph:
https://s3.us-west-2.amazonaws.com/czi.paolo-public/HG002-Guppy-6.0.6-UL-run14/Assembly-Phased.gfa

And it crashes on my machine as soon as I click Draw. No error message, the window just closes.

I have 32GB of RAM and I use Ubuntu 20.04, running the release from here:
https://github.com/asl/BandageNG/releases/download/v2022.06/BandageNG-2022.06-x86_64.AppImage

**Comment by asl** [comment] 2022-07-15 21:21
@rlorigro Is there anything about OOM in the system log?

**Comment by rlorigro** [comment] 2022-07-15 21:36
It doesn't look like there is anything specifically to do with memory, but this is in the log:
```
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]: #033[31;1merror: #033[0mwhile parsing GFA segment
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]:      │
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]:    1 │ S#033[2m⇨#033[0mPR.7193.1.11.0#033[2m⇨#033[0m#033[31;1m⇨#033[0mLN:i:0
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]:      │                  #033[31;1m^ exhausted choice
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]: #033[0m
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]: #033[31;1merror: #033[0mwhile parsing GFA segment
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]:      │
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]:    1 │ S#033[2m⇨#033[0mPR.7197.1.177.0#033[2m⇨#033[0m#033[31;1m⇨#033[0mLN:i:0
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]:      │                   #033[31;1m^ exhausted choice
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]: #033[0m
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]: #033[31;1merror: #033[0mwhile parsing GFA segment
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]:      │
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]:    1 │ S#033[2m⇨#033[0mPR.7197.1.177.1#033[2m⇨#033[0m#033[31;1m⇨#033[0mLN:i:0
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]:      │                   #033[31;1m^ exhausted choice
Jul 15 14:31:22 computron org.gnome.Nautilus[11164]: #033[0m
Jul 15 14:31:38 computron kernel: [ 8685.933861] traps: Thread (pooled)[11175] trap invalid opcode ip:5587c4bc02cf sp:7fc71da76920 error:0 >
Jul 15 14:31:38 computron systemd[1]: tmp-.mount_Bandag0gC93m.mount: Succeeded.
Jul 15 14:31:38 computron systemd[1157]: tmp-.mount_Bandag0gC93m.mount: Succeeded.
Jul 15 14:31:38 computron systemd[1848]: tmp-.mount_Bandag0gC93m.mount: Succeeded.
```

there are many more of the GFA segment parsing errors, probably one for every one of the "PR" segments in the file.

**Comment by rlorigro** [comment] 2022-07-15 21:46
On second glance, these are all the 0 length nodes, I believe. This was clipped in my previous message: `LN:i:0`

**Comment by asl** [comment] 2022-07-15 21:46
We do not have a good way to report GFA parsing errors as of now. So we just print them to stderr and ignore malformed records. Thought, it's should be unrelated to the crash.

It looks like OGDF wants to use some AVX stuff which your system lacks, right?

**Comment by rlorigro** [comment] 2022-07-15 21:49
Hmm I'm not sure. I've successfully compiled and run OGDF on this machine for a project of my own, but it could be something related to how you've built the executable.

**Comment by asl** [comment] 2022-07-15 21:50
OGDF compiles with `-march=native` by default. So essentially translates the features of the build platform...

**Comment by asl** [comment] 2022-07-15 21:50
As for your file, it is indeed malformed. We are having:

```
S       PR.19.3.319.1           LN:i:0
```

You're lacking a sequence field.

**Comment by rlorigro** [comment] 2022-07-15 21:52
I think there are technically enough tab delimiters in this file, but the field is empty because the sequence length is 0

**Comment by asl** [comment] 2022-07-15 21:54
> I think there are technically enough tab delimiters in this file, but the field is empty because the sequence length is 0

Please refer to the GFA spec: https://github.com/GFA-spec/GFA-spec/blob/master/GFA1.md. The sequence field cannot be empty (regexp for this field is `\*|[A-Za-z=.]+`). You need to place `*` placeholder if the sequence is missed (or empty).

**Comment by rlorigro** [comment] 2022-07-15 21:56
Ok. @paoloczi is the author of the Shasta assembler, which generates these files:
https://github.com/chanzuckerberg/shasta

**Comment by asl** [comment] 2022-07-15 21:59
As for the layout – I was able to generate layout, so I believe the problem is due to OGDF using AVX (I know problem for sure because one cannot run OGDF compiled for x86-64 on Mac M1 via Rosetta 2, we are building fat binaries for release).

So, the only workaround for now is to compile from sources... I will take care about binaries for the next BandageNG release.

**Comment by rlorigro** [comment] 2022-07-15 22:01
Here's my CPU info:
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
stepping        : 9
microcode       : 0xea
cpu MHz         : 4363.519
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
vmx flags       : vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple shadow_vmcs pml ept_mode_based_exec
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit srbds
bogomips        : 8400.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:
```

**Comment by paoloczi** [comment] 2022-07-15 22:04
According to the GFA specification, the `*` should be used to indicate that the sequence is unspecified, not that it is empty. In these cases, the sequence is actually specified, and consisting 0 bases. The GFA specification does not forbid specifying a sequence with zero length. 

In a phased assembly there are good reasons to do this, to describe the two haplotypes at a heterozygous insertion or deletion. The alternative of suppressing the empty segment has other disadvantages.

**Comment by asl** [comment] 2022-07-15 22:05
> According to the GFA specification, the `*` should be used to indicate that the sequence is unspecified, not that it is empty. In these cases, the sequence is actually specified, and consisting 0 bases. The GFA specification does not forbid specifying a sequence with zero length.
> 
> In a phased assembly there are good reasons to do this, to describe the two haplotypes at a heterozygous insertion or deletion. The alternative of suppressing the empty segment has other disadvantages.

It does. The regexp is `\*|[A-Za-z=.]+`. So it should be either `*` or one or more characters. So in this case it should be `*` with `LN` tag of zero length.

**Comment by asl** [comment] 2022-07-15 22:08
> Here's my CPU info:
> 
> ```
> processor       : 0
> vendor_id       : GenuineIntel
> cpu family      : 6
> model           : 158
> model name      : Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
> stepping        : 9
> microcode       : 0xea
> cpu MHz         : 4363.519
> cache size      : 8192 KB
> physical id     : 0
> siblings        : 8
> core id         : 0
> cpu cores       : 4
> apicid          : 0
> initial apicid  : 0
> fpu             : yes
> fpu_exception   : yes
> cpuid level     : 22
> wp              : yes
> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
> vmx flags       : vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple shadow_vmcs pml ept_mode_based_exec
> bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit srbds
> bogomips        : 8400.00
> clflush size    : 64
> cache_alignment : 64
> address sizes   : 39 bits physical, 48 bits virtual
> power management:
> ```

@rlorigro Then I'm confused... looks like everything should be supported. However, we're seeing in the log:
```
Jul 15 14:31:38 computron kernel: [ 8685.933861] traps: Thread (pooled)[11175] trap invalid opcode ip:5587c4bc02cf sp:7fc71da76920 error:0 >
```
Are you able to recompile from the sources?

**Comment by paoloczi** [comment] 2022-07-15 22:10
True, the regexp says there should be something, even though the description in word says nothing about that. So it sounds like for the case of empty sequence I should continue to write the length as 0, but write the sequence as `*` instead of leaving it empty? If there is agreement on this I can make this change on Monday, and provide @rlorigro a test build with the fix.

**Comment by paoloczi** [comment] 2022-07-15 22:12
@rlorigro regarding the invalid opcode, there should be a message somewhere containing the opcode that caused the trap. From the opcode we can then find the missing instruction.

**Comment by asl** [comment] 2022-07-15 22:13
> True, the regexp says there should be something, even though the description in word says nothing about that. So it sounds like for the case of empty sequence I should continue to write the length as 0, but write the sequence as `*` instead of leaving it empty? If there is agreement on this I can make this change on Monday, and provide @rlorigro a test build with the fix.

Yes. In case of Bandage `*` is internally represented as a (compressed) sequence of 'N' of `LN` length. So, it will be exactly zero-length string here :)

**Comment by rlorigro** [comment] 2022-07-15 22:14
This is the entire message:
```
Jul 15 14:31:38 computron kernel: [ 8685.933861] traps: Thread (pooled)[11175] trap invalid opcode ip:5587c4bc02cf sp:7fc71da76920 error:0 in BandageNG[5587c4a39000+20b000]
```

Compiling from source would require installing qt6 on ubuntu20.04, which, from my memory was not simple

**Comment by asl** [comment] 2022-07-15 22:16
> This is the entire message:
> 
> ```
> Jul 15 14:31:38 computron kernel: [ 8685.933861] traps: Thread (pooled)[11175] trap invalid opcode ip:5587c4bc02cf sp:7fc71da76920 error:0 in BandageNG[5587c4a39000+20b000]
> ```
> 
> Compiling from source would require installing qt6 on ubuntu20.04, which, from my memory was not simple

Ok. Let me check if can disable using `-march=native` for OGDF and do some snapshot for you.

**Comment by paoloczi** [comment] 2022-07-15 22:25
From that message and a hex or disassembled dump of the executable it should be possible to find the offending instruction. It looks like your machine lacks the avx512 extensions - it could be that.

@asl for the executables included in releases, it would be best not to assume the latest extensions. That is, either no `-march=native`, or just assume some of the older extensions that are likely to be available on most machines in use today.

**Comment by asl** [comment] 2022-07-15 22:29
@paoloczi Yes, I just want to get rid of `-march=native`. Apparently this is OGDF default :)

**Comment by asl** [comment] 2022-07-15 22:35
@rlorigro It's building now. So hopefully will be in 30-40 minutes or so.

**Comment by asl** [comment] 2022-07-15 22:57
@rlorigro Can you please check: https://github.com/asl/BandageNG/releases/download/v2022.07.16/BandageNG-f3ca6e0-x86_64.AppImage ?

**Comment by rlorigro** [comment] 2022-07-15 22:59
It gives me a 404 error

**Comment by asl** [comment] 2022-07-15 22:59
Sorry, updated link just now

**Comment by rlorigro** [comment] 2022-07-15 23:05
Yes its working now :+1: 

One unrelated thing though, it seems to arrange the connected components in a line, instead of packing them in a rectangle like the original Bandage, which was my preference.

**Comment by asl** [comment] 2022-07-15 23:06
It does pack them. However, slightly differently – optimizing the overall space.

**Comment by asl** [comment] 2022-07-15 23:07
Great, thanks! So this might be closed then :)

**Closed as completed by asl** 2022-07-15 23:07 UTC
Labels: bug

**Comment by rlorigro** [comment] 2022-07-15 23:16
Hmm ok. Well this has for some reason put every component in one row, which doesn't seem very space efficient
![image](https://user-images.githubusercontent.com/28764332/179323057-eaecb73d-7bad-4a36-8b13-a149162a625f.png)

Compare this to the original packing method:
![image](https://user-images.githubusercontent.com/28764332/179323283-7a4c86fe-a73f-479f-9483-cb48e6ac452e.png)

**Comment by asl** [comment] 2022-07-15 23:18
Interesting. Something is broken in newer OGDF then :)

What is the node length per Mbp settings in your case?

**Comment by rlorigro** [comment] 2022-07-15 23:19
Original Bandage: Auto: 551.5

**Comment by rlorigro** [comment] 2022-07-15 23:22
And BandageNG has the same outcome: 551.5. Both are default/auto

**Comment by asl** [comment] 2022-07-15 23:23
Ok, great. I will try to see why OGDF does such weird layout

**Comment by rlorigro** [comment] 2022-07-15 23:28
Ok thanks for your help. BandageNG is definitely faster during the layout, though.
